### ISSUE TITLE
Error can't login

### ISSUE THREAD

**Issue by Aymendje** [seanwlk/tvtimewrapper#2]
When running

```
from tvtimewrapper import TVTimeWrapper
tvtime = TVTimeWrapper("username","password")
```

(I evidently changed my username and password to the real one)
I am getting an error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aymen/.local/lib/python3.9/site-packages/tvtimewrapper/__init__.py", line 27, in __init__
    raise TVTimeLoginError(r['message'])
tvtimewrapper.exceptions.TVTimeLoginError: Can not log-in
```

I am using Python 3.9.2 in WSL

**Comment by seanwlk** [comment]
Hi, i just tried on my WSL with python 3.9.5 and i have no issues with the login, another user in #1 had this issue and i can't troubleshoot that since both my main TVTime account and testing one had no issues with the login. Can you try making a new account just to see if it works ?  

I do not have enough data to resolve this issue. Is you account a tvtime one or a "sign in with twitter / facebook" one ? those require Oauth2 i assume, i havent checked that and just reverse engineered the main app login with their service but i assume the HTTP session has to be working the same way

**Comment by Aymendje** [comment]
For some reasons, I am still unable to use it.
I tried 2 different accounts, both with password (but facebook linked)
For now, I mitigated this by using an html parser instead with beautifulsoup.

**Comment by seanwlk** [comment]
Then I assume the issue is Facebook. Even though my main account is linked with Facebook and i can login (originally registered from tvtime site and then linked). I just created another account and works fine so I'm just confused.
The first version of this library was running with beautifulsoup
